server:
  port: 8084
spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    default-schema: whitelabel
  datasource:
    username: postgres
    password: sz!]FH(ySqQR
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      repositories:
        enabled: false
      password: 123456
      host: localhost
      port: 6379