apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-config
---
apiVersion: v1
kind: Secret
metadata:
  name: notify-redis-credentials
data:
  password: cGFzc3dvcmQxMjMK
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: notify-mongo-credentials
data:
  password: U1l3NXZWSzRHalRYYkxOcFVpbzh2cG04
  user: R3plWjE1czFFUElIa2VrQ0xSYTNtMVZt
  database: bm90aWZ5X3NlcnZpY2U=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: notify-rabbit-credentials
data:
  password: Z3Vlc3Q=
  user: Z3Vlc3Q=
type: Opaque
