apiVersion: v1
kind: Service
metadata:
  name: service-notify-schedule
spec:
  selector:
    name: deployment-notify-schedule
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-notify-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment-notify-schedule
  template:
    metadata:
      labels:
        name: deployment-notify-schedule
    spec:
      containers:
        - name: notify-schedule
          image: gabrielbessadev/notify-schedule:0.0.1-SNAPSHOT
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: spring.data.redis.password
              valueFrom:
                secretKeyRef:
                  name: notify-redis-credentials
                  key: password
            - name: spring.data.redis.port
              value: '6379'
            - name: spring.data.redis.host
              value: service-notify-redis
            - name: spring.data.mongodb.host
              value: service-notify-mongo
            - name: spring.data.mongodb.database
              value: notify-service
            - name: spring.data.mongodb.authentication-database
              value: admin
            - name: spring.data.mongodb.username
              valueFrom:
                secretKeyRef:
                  name: notify-mongo-credentials
                  key: user
            - name: spring.data.mongodb.password
              valueFrom:
                secretKeyRef:
                  name: notify-mongo-credentials
                  key: password
            - name: spring.rabbitmq.host
              value: service-notify-rabbit
            - name: spring.rabbitmq.username
              valueFrom:
                secretKeyRef:
                  key: user
                  name: notify-rabbit-credentials
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: notify-rabbit-credentials
            - name: spring.rabbitmq.port
              value: '5672'
          resources:
            requests:
              memory: "400Mi"
              cpu: "100m"
            limits:
              memory: "6000Mi"
              cpu: "300m"